codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
coverage:
  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project:
      default:
        enabled: yes
        threshold: null
        target: auto
        if_ci_failed: error
    patch:
      default:
        enabled: yes